/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Ramsim;

import Ramsim.Ramsim;

public class App {
  public static void main(String[] args) {
    Ramsim rms = new Ramsim("tests_ram/test2.ram",
                            "input.txt", "output.txt", true);
    rms.execute();
  }
}
